### ISSUE TITLE
Requesting data on inherited inactive compounds 

### ISSUE THREAD

**Issue by fidiris** [OpenSourceTB/OSTB_Series_3#1]
Inherited compounds from GSK are listed below which were found to be inactive against NR Mtb. We are in the process of requesting the raw biological data. This will help us to prepare for the next stages of lead optimisation. 

![Inherited inactive compounds](https://user-images.githubusercontent.com/48478874/54743908-6d875a80-4bbd-11e9-8f4d-a0b7246b43ca.png)

**Comment by mattodd** [comment]
I'll reach out to GSK on this point. I also recall many of these compounds were uploaded to Collaborative Drug Discovery, and will dig up the details so that we can maintain full links. On me.

**Comment by mattodd** [comment]
Still working on this. It appears as though the compounds were made by Thulasi Warrier ([1st author on the only other paper](https://pubs.acs.org/doi/abs/10.1021/acsinfecdis.5b00025)), and we're trying to track the data down. There are a lot of compounds here.

**Comment by MFernflower** [comment]
Interesting to see how perseverant they were in trying to move away from the halophenol cores! - I wonder if our hit inhibits fatty acid synthesis like the sorta similar-looking triclosan?? @fidiris @mattodd 


![5363](https://user-images.githubusercontent.com/3164942/70406641-73ed8900-1a0f-11ea-99ad-8211ddb0e215.png)
